feat(apache): support check license header with RAT client model
apache/incubator-hugegraph-toolchain pull request #352
Opened 2022-10-31 08:14 UTC by JackyYangPassion

support check license header with RAT client model

```
1. Introduce rat pugin plugin in pom
2. Idea configuration copyright template
3. Discover stock files with mvn apache-rat:check
4. Configure automated detection in each module's ci
   client
   hubble
   loader
Reference：
https://github.com/apache/incubator-hugegraph-commons/pull/108
```

2022-10-31 08:39 UTC, simon824 commented on .github/workflows/client-ci.yml
> +
I think we'd better throw the exception instead of printing it

2022-10-31 08:46 UTC, z7658329 commented
the same as #338 ?

2022-10-31 09:08 UTC, imbajin commented on .github/workflows/client-ci.yml
> +
> I think we'd better throw the exception instead of printing it

any suggestion? it's hard to define `error` now (or any reference from other apache repo?)

2022-10-31 11:04 UTC, simon824 commented on .github/workflows/client-ci.yml
> +
> any suggestion? it's hard to define `error` now (or any reference from other apache repo?)

maybe can refer to [this](https://github.com/apache/incubator-kyuubi/blob/master/.github/workflows/license.yml)

2022-10-31 11:30 UTC, imbajin commented on .github/workflows/client-ci.yml
> +
> > any suggestion? it's hard to define `error` now (or any reference from other apache repo?)
> 
> maybe can refer to [this](https://github.com/apache/incubator-kyuubi/blob/master/.github/workflows/license.yml?rgh-link-date=2022-10-31T11%3A04%3A47Z)

Thanks, someone could try it later and unify it in all repos (could add low priority in the summary issue, we need focus high & normal issues first)

2022-11-01 00:57 UTC, simon824 commented on .github/workflows/client-ci.yml
> +
I'm not sure, we can test it in this pr.

2022-11-01 14:16 UTC, imbajin commented on .github/workflows/client-ci.yml
> +
OK, @JackyYangPassion you could rebase the master and continue to try it

2022-11-02 15:11 UTC, JackyYangPassion commented on .github/workflows/client-ci.yml
> +
ok

2022-11-02 15:11 UTC, JackyYangPassion commented on .github/workflows/client-ci.yml
> +
ok

2022-11-02 15:24 UTC, javeme submitted a review, later dismissed

2022-11-03 06:42 UTC, JackyYangPassion commented on .github/workflows/client-ci.yml
> +
> I think we'd better throw the exception instead of printing it
do you mean like this? 
![image](https://user-images.githubusercontent.com/13795366/199660925-11fa5ccb-8274-4cbe-9d39-c8debee3f231.png)

2022-11-03 15:01 UTC, imbajin commented on .github/workflows/client-ci.yml
> +
> > I think we'd better throw the exception instead of printing it
> > do you mean like this?
> > ![image](https://user-images.githubusercontent.com/13795366/199660925-11fa5ccb-8274-4cbe-9d39-c8debee3f231.png)

yes, alert all errors is better. like add a a maven param (to not stop it)

2022-11-07 01:33 UTC, JackyYangPassion commented on .github/workflows/client-ci.yml
> +
ok

2022-11-07 13:33 UTC, javeme approved these changes

2022-11-07 14:42 UTC, imbajin approved these changes
shall we use the original rat-step in each module? Or just clean them

2022-11-08 12:37 UTC, javeme submitted a review, later dismissed

2022-11-08 12:44 UTC, imbajin requested changes
refer https://github.com/apache/incubator-hugegraph/pull/2009

and use a unified way in all repos

2022-11-09 13:18 UTC, JackyYangPassion commented
> refer [apache/incubator-hugegraph#2009](https://github.com/apache/incubator-hugegraph/pull/2009)
> 
> and use a unified way in all repos

ok

2022-11-09 13:28 UTC, javeme commented on .github/workflows/license-checker.yml
> +          config: .licenserc.yaml
expect a blank line

2022-11-09 13:28 UTC, javeme commented on .licenserc.yaml
> +  license-location-threshold: 80
ditto

2022-11-09 15:07 UTC, javeme commented on .github/workflows/license-checker.yml
> +          message: 'Automatic application of license header'
expect a blank line

2022-11-09 17:41 UTC, javeme approved these changes

2022-11-10 05:46 UTC, imbajin commented
the same question in server, how could it add the license automatically? currently, it throws problems only

<img width="849" alt="image" src="https://user-images.githubusercontent.com/17706099/201010375-a195b70d-1385-4113-babd-12d9b55b59d9.png">

2022-11-10 05:47 UTC, imbajin commented on .licenserc.yaml
> +    - 'hugegraph-hubble/hubble-fe/*'
why we ignore `fe` files?

2022-11-10 05:48 UTC, imbajin commented on .github/workflows/license-checker.yml
> +        uses: apache/skywalking-eyes@main
add a URL comment upon so that we could get the **official doc** easily

2022-11-10 05:49 UTC, imbajin commented on .github/workflows/license-checker.yml
> +      - uses: actions/checkout@v2
use v3

2022-11-10 08:48 UTC, JackyYangPassion commented
> the same question in server, how could it add the license automatically? currently, it throws problems only
> 
> <img alt="image" width="849" src="https://user-images.githubusercontent.com/17706099/201010375-a195b70d-1385-4113-babd-12d9b55b59d9.png">

It was verified last night that it didn't work. I'll solve it later

2022-11-22 14:07 UTC, coderzc commented on .github/workflows/license-checker.yml
> +      - uses: actions/checkout@v2
```suggestion
      - uses: actions/checkout@v3
```

2022-11-22 15:00 UTC, javeme commented
license check error:
```js
INFO Totally checked 1547 files, valid: 710, invalid: 251, ignored: 586, fixed: 0 
ERROR the following files don't have a valid license header: 
hugegraph-dist/pom.xml
hugegraph-hubble/.prettierrc
hugegraph-hubble/.stylelintrc
hugegraph-hubble/hubble-be/pom.xml
hugegraph-hubble/hubble-be/src/main/java/org/apache/hugegraph/entity/schema/SchemaConflict.java
hugegraph-hubble/hubble-be/src/main/resources/database/data.sql
hugegraph-hubble/hubble-be/src/main/resources/database/schema.sql
```

2022-11-25 16:11 UTC, javeme commented
there are still some license checker errors:
```c
ERROR the following files don't have a valid license header: 
LICENSE
hugegraph-dist/pom.xml
hugegraph-dist/release-docs/LICENSE
hugegraph-dist/release-docs/NOTICE
hugegraph-hubble/hubble-be/pom.xml
hugegraph-hubble/hubble-be/src/main/java/org/apache/hugegraph/entity/schema/SchemaConflict.java
hugegraph-hubble/hubble-be/src/main/resources/database/data.sql
hugegraph-hubble/hubble-be/src/main/resources/database/schema.sql
hugegraph-hubble/hubble-be/src/test/python/check_server_status.feature
hugegraph-hubble/hubble-be/src/test/python/steps/check_server_status.py
hugegraph-hubble/hubble-be/src/test/resources/database/data.sql
hugegraph-hubble/hubble-be/src/test/resources/database/schema.sql
hugegraph-hubble/hubble-be/src/test/resources/files/file_with_empty_line
hugegraph-hubble/hubble-be/src/test/resources/files/file_without_empty_line
hugegraph-hubble/hubble-dist/pom.xml
hugegraph-hubble/hubble-fe/.env
hugegraph-hubble/hubble-fe/config-overrides.js
hugegraph-hubble/hubble-fe/public/index.html
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_add.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_add_node.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_arrow.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_arrow_[16](https://github.com/apache/incubator-hugegraph-toolchain/actions/runs/3548491925/jobs/5959758228#step:4:17).svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_arrow_blue.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_arrow_selected.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_arrow_white.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_back_[32](https://github.com/apache/incubator-hugegraph-toolchain/actions/runs/3548491925/jobs/5959758228#step:4:33).svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_back_32_normal.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_back_32_pressed.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_biaoge_hover.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_biaoge_normal.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_biaoge_pressed.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_cebianshouqi.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_cebianzhankai.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_close_16.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_close_white.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_daorushuju_normal.svg
hugegraph-hubble/hubble-fe/src/assets/imgs/ic_daorushuju_pressed.svg
hugegraph-hubble/hubble-fe/src/stores/index.ts
hugegraph-hubble/hubble-fe/src/stores/types/GraphManagementStore/asyncTasksStore.ts
hugegraph-hubble/hubble-fe/src/stores/types/GraphManagementStore/dataAnalyzeStore.ts
hugegraph-hubble/hubble-fe/src/stores/types/GraphManagementStore/dataImportStore.ts
hugegraph-hubble/hubble-fe/src/stores/types/GraphManagementStore/graphManagementStore.ts
hugegraph-hubble/hubble-fe/src/stores/types/GraphManagementStore/metadataConfigsStore.ts
hugegraph-hubble/hubble-fe/src/stores/types/common.ts
hugegraph-hubble/hubble-fe/src/stores/utils/index.ts
hugegraph-hubble/hubble-fe/src/third-party.d.ts
hugegraph-hubble/hubble-fe/src/utils/calcAlgorithmFormWidth.ts
hugegraph-hubble/hubble-fe/src/utils/convertStringToJSON.ts
hugegraph-hubble/hubble-fe/src/utils/filterEmptyAlgorightmParams.ts
hugegraph-hubble/hubble-fe/src/utils/formatAlgorithmStatement.ts
hugegraph-hubble/hubble-fe/src/utils/getUnicodeLength.ts
hugegraph-hubble/hubble-fe/src/utils/index.ts
hugegraph-hubble/hubble-fe/src/utils/isDataTypeNumeric.ts
hugegraph-hubble/hubble-fe/yarn.lock
hugegraph-loader/assembly/static/example/spark/schema.groovy 
ERROR one or more files does not have a valid license header
```

2022-11-25 16:12 UTC, javeme commented on .licenserc.yaml
> +    - 'hugegraph-hubble/*'
'hugegraph-hubble/**'?

2022-11-28 06:08 UTC, JackyYangPassion commented on .licenserc.yaml
> +    - 'hugegraph-hubble/*'
just ignore *.ts *.tsx *.less file

2022-11-28 06:44 UTC, imbajin commented
could also exclude `yarn.lock` file

2022-11-28 09:42 UTC, JackyYangPassion commented
> > the same question in server, how could it add the license automatically? currently, it throws problems only
> > <img alt="image" width="849" src="https://user-images.githubusercontent.com/17706099/201010375-a195b70d-1385-4113-babd-12d9b55b59d9.png">
> 
> It was verified last night that it didn't work. I'll solve it later

add license automatically with cmd:
```
docker run -it --rm -v $(pwd):/github/workspace apache/skywalking-eyes header fix
```

2022-11-28 09:55 UTC, imbajin commented on hugegraph-hubble/hubble-be/src/main/java/org/apache/hugegraph/entity/schema/SchemaConflict.java
>   * Copyright (C) 2019 Baidu, Inc. All Rights Reserved.
remove this line (I fix it)

2022-11-28 09:58 UTC, imbajin approved these changes

2022-11-28 14:18 UTC, javeme approved these changes

2022-11-28 14:19 UTC, merged

2023-02-14 05:41 UTC, imbajin commented
invalid file:
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/17706099/218649407-ffab9f28-3b13-4183-a951-ad12afcb3128.png">